# Bibliotecas

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Primeira olhada no DF

In [ ]:
df = pd.read_csv('C:\Arquivos Vsco\Projeto Serenatto\data\serenatto_2sem_2023.csv')
df.head()

<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
<>:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
C:\Users\user\AppData\Local\Temp\ipykernel_8348\2251040531.py:1: SyntaxWarning: "\A" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\A"? A raw string is also an option.
  df = pd.read_csv('C:\Arquivos Vsco\Projeto Serenatto\data\serenatto_2sem_2023.csv')

     id        data           produto  valor   metodo_pagamento
0  2720  2023-07-01  Risoto de Funghi   13.0   Cartão de Débito
1  2721  2023-07-02          Tiramisù   10.0   Cartão de Débito
2  2722  2023-07-02          Tiramisù   10.0  Cartão de Crédito
3  2723  2023-07-02       Ratatouille    8.5                PIX
4  2724  2023-07-03       Ratatouille    8.5           Dinheiro

In [ ]:
df.describe()

                id       valor
count   856.000000  856.000000
mean   3147.500000    7.619159
std     247.250211    3.174247
min    2720.000000    2.500000
25%    2933.750000    4.500000
50%    3147.500000    8.000000
75%    3361.250000   10.500000
max    3575.000000   13.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856 entries, 0 to 855
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                856 non-null    int64
 1   data              856 non-null    object
 2   produto           856 non-null    object
 3   valor             856 non-null    float64
 4   metodo_pagamento  856 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 33.6+ KB

A coluna de data não está classificada como data, isso talvez possa prejudicar futuras análises

In [ ]:
df.isnull().sum()

id                  0
data                0
produto             0
valor               0
metodo_pagamento    0
dtype: int64

Não há nenhum valor nulo

# Tratando a data

In [ ]:
#Convertendo a coluna de data para o tipo correto
df['data'] = pd.to_datetime(df['data'])


#Criando coluna de mês
df['mes'] = df['data'].dt.month

df['mes_nome'] = df['data'].dt.strftime('%b')


df.head()

     id       data           produto  valor   metodo_pagamento  mes mes_nome
0  2720 2023-07-01  Risoto de Funghi   13.0   Cartão de Débito    7      Jul
1  2721 2023-07-02          Tiramisù   10.0   Cartão de Débito    7      Jul
2  2722 2023-07-02          Tiramisù   10.0  Cartão de Crédito    7      Jul
3  2723 2023-07-02       Ratatouille    8.5                PIX    7      Jul
4  2724 2023-07-03       Ratatouille    8.5           Dinheiro    7      Jul

In [ ]:
df.tail()

       id       data           produto  valor   metodo_pagamento  mes mes_nome
851  3571 2023-12-31            Panini    7.5                PIX   12      Dec
852  3572 2023-12-31  Pizza Margherita   12.0           Dinheiro   12      Dec
853  3573 2023-12-31        Bruschetta    7.0           Dinheiro   12      Dec
854  3574 2023-12-31           Gnocchi   10.5   Cartão de Débito   12      Dec
855  3575 2023-12-31           Macaron    3.5  Cartão de Crédito   12      Dec

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856 entries, 0 to 855
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                856 non-null    int64
 1   data              856 non-null    datetime64[ns]
 2   produto           856 non-null    object
 3   valor             856 non-null    float64
 4   metodo_pagamento  856 non-null    object
 5   mes               856 non-null    int32
 6   mes_nome          856 non-null    object
dtypes: datetime64[ns](1), float64(1), int32(1), int64(1), object(3)
memory usage: 43.6+ KB

# Análise exploratória inicial dos dados

In [ ]:
#Quais produtos tem no dataset
print('produtos:', df['produto'].unique())

#Quais os métodos de pagamento presente
print('\n\nmet.pgmt:', df['metodo_pagamento'].unique())

#Qual período o dataset cobre
print('\n\nperiíodo:', df['data'].min(), 'até: ', df['data'].max())

produtos: ['Risoto de Funghi' 'Tiramisù' 'Ratatouille' 'Salada Niçoise'
 'Café au lait' 'Lasanha' 'Gnocchi' 'Espresso' 'Macaron' 'Gelato' 'Éclair'
 'Canapé de Salmão' 'Limoncello' 'Cappuccino' 'Pizza Margherita' 'Baguete'
 'Croissant' 'Bruschetta' 'Quiche Lorraine' 'Panini']


met.pgmt: ['Cartão de Débito' 'Cartão de Crédito' 'PIX' 'Dinheiro']


periíodo: 2023-07-01 00:00:00 até:  2023-12-31 00:00:00

In [ ]:
#Produto mais vendido
print('top5 produtos mais pedidos: ')
df['produto'].value_counts().head()

top5 produtos mais pedidos:

produto
Café au lait        53
Gnocchi             50
Canapé de Salmão    48
Macaron             47
Risoto de Funghi    46
Name: count, dtype: int64

In [ ]:
#Receita total
print(f'receita total: R$ {df['valor'].sum():.2f}')

#Ticket médio por cliente
print(f'\n\nticket médio: R$ {df['valor'].mean():.2f}')

receita total: R$ 6522.00


ticket médio: R$ 7.62

## Hipótese 1: produtos baratos são mais vendidos?

In [ ]:
# tabela de preço
produtos_valores = df.groupby('valor')['produto'].unique()
produtos_valores

valor
2.5             [Espresso]
3.0              [Baguete]
3.5              [Macaron]
4.0         [Café au lait]
4.5               [Éclair]
5.0            [Croissant]
5.5           [Cappuccino]
6.0               [Gelato]
7.0           [Bruschetta]
7.5               [Panini]
8.0      [Quiche Lorraine]
8.5          [Ratatouille]
9.0           [Limoncello]
9.5     [Canapé de Salmão]
10.0            [Tiramisù]
10.5             [Gnocchi]
11.0      [Salada Niçoise]
11.5             [Lasanha]
12.0    [Pizza Margherita]
13.0    [Risoto de Funghi]
Name: produto, dtype: object

In [ ]:
# filtro < 8
produtos_menor_que8 = df.query('valor < 8')['produto'].unique()
produtos_menor_que8

array(['Café au lait', 'Espresso', 'Macaron', 'Gelato', 'Éclair',
       'Cappuccino', 'Baguete', 'Croissant', 'Bruschetta', 'Panini'],
      dtype=object)

In [ ]:
produtos_mais_vendidos = df['produto'].value_counts()
produtos_mais_vendidos

produto
Café au lait        53
Gnocchi             50
Canapé de Salmão    48
Macaron             47
Risoto de Funghi    46
Tiramisù            46
Limoncello          46
Salada Niçoise      45
Espresso            44
Éclair              43
Panini              43
Lasanha             41
Baguete             41
Quiche Lorraine     41
Gelato              40
Pizza Margherita    39
Ratatouille         38
Cappuccino          38
Bruschetta          37
Croissant           30
Name: count, dtype: int64

## Hipótese testada: produtos baratos são mais vendidos?

Criei um filtro de produtos abaixo de R$ 8,00 e comparei com 
os mais vendidos. 

**Resultado: NÃO CONFIRMADO**

Exemplo contrário: Bruschetta custa R$ 6,90 (bem abaixo dos 
R$ 7,50 de ticket médio) mas é apenas o 2º produto MENOS 
vendido. Isso sugere que o preço sozinho NÃO é o fator 
decisivo na preferência do cliente.

**Verificar Possíveis fatores que implicam nesse resultado:**
- Ver se tem sazonalidade (vendas variam por mês?)
- Cruzar com método de pagamento